### ISSUE TITLE
How to use the published npm package to verdaccio?

### ISSUE THREAD

**Issue by LakshmiRavali** [verdaccio/github-actions#15]
I am using verdaccio/github-actions/publish action, I want to install the package after it publish How to do this?

Example:
```
- uses: actions/checkout@v2
- name: Publish
  uses: verdaccio/github-actions/publish@v0.4.0
  with:
   args: -d
  env:
   NODE_ENV: development
- name: Install the published release
?
```
